### ISSUE TITLE
The linked Heroku app is down

### ISSUE THREAD

**Issue by bbrewington** [samuelklam/airbnb-pricing-prediction#41]
This link from repo description: https://airbnb-pricing-prediction.herokuapp.com/

Gave this error:

<img width="601" alt="Screenshot 2022-12-11 at 2 38 29 PM" src="https://user-images.githubusercontent.com/10573749/206924977-5c72c522-db2b-49ba-bfa4-caf46c4f2b07.png">

**Comment by samuelklam** [comment]
Resolved: https://github.com/samuelklam/airbnb-pricing-prediction/commit/93c49f679c7b79366413818568aca77ddd69f559
